apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: YXNkZjEyMzQ=  # Base64 encoded "asdf1234"
  mysql-password: YXNkZjEyMzQ=       # Base64 encoded "asdf1234"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: expense_tracker
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: django-app  # Use your local Docker image
        imagePullPolicy: Never
        env:
        - name: DJANGO_SECRET_KEY
          value: "django-insecure-6uh*ef&_tjq($l0oa&fv*nl(^%o=m5)j2n)hwi3s^8=7pw#m9%"
        - name: DEBUG
          value: "True"
        - name: DJANGO_ALLOWED_HOSTS
          value: "localhost,127.0.0.1"
        - name: DATABASE_ENGINE
          value: "django.db.backends.mysql"
        - name: DATABASE_NAME
          value: "expense_tracker"
        - name: DATABASE_USERNAME
          value: "root"  # Root is now directly set
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DATABASE_HOST
          value: "mysql"  # Matches the MySQL service name
        - name: DATABASE_PORT
          value: "3306"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
